{{ if (index .Values "gateway" "enabled") }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ace
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: ace
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    {{ if .Values.gateway.tls.enabled }}
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ default (printf "%s-cert" (include "acaas.fullname" .)) .Values.gateway.tls.secret.name }}
        namespace: {{ .Release.Namespace }}
    {{- end }}
    allowedRoutes:
      namespaces:
        from: Same
{{- end }}
