apiVersion: v2
name: cluster-importer
description: A Helm chart for Kubernetes
type: application
version: v2026.2.16
appVersion: v0.2.0
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
