apiVersion: ui.k8s.appscode.com/v1alpha1
kind: Feature
metadata:
  name: kubevault-opscenter
spec:
  title: Kubevault Opscenter
  description: |
    UI and monitoring resources for Kubevault.
  icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/cluster.svg
      type: image/svg+xml
  featureSet: opscenter-security
  featureBlock: kubevault
  required: false
  requirements:
    features:
    - kubevault
  readinessChecks:
    workloads:
      - group: apps
        version: v1
        kind: Deployment
        selector:
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: kubevault-ui-server
  chart:
    name: kubevault-opscenter
    namespace: kubevault
    version: "v2023.03.03"
    sourceRef:
      kind: HelmRepository
      name: kubevault
      namespace: {{ .Release.Namespace }}
