apiVersion: v1
description: Kubernetes license-proxyserver by AppsCode
name: license-proxyserver
version: v2024.2.25
appVersion: v0.0.9
home: https://github.com/bytebuilders/license-proxyserver
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/bytebuilders/license-proxyserver
maintainers:
- name: appscode
  email: support@appscode.com
