properties:
  affinity:
    properties:
      nodeAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                preference:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchFields:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                  type: object
                weight:
                  format: int32
                  type: integer
              required:
              - preference
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            properties:
              nodeSelectorTerms:
                items:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchFields:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                  type: object
                type: array
            required:
            - nodeSelectorTerms
            type: object
        type: object
      podAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                podAffinityTerm:
                  properties:
                    labelSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    namespaceSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    namespaces:
                      items:
                        type: string
                      type: array
                    topologyKey:
                      type: string
                  required:
                  - topologyKey
                  type: object
                weight:
                  format: int32
                  type: integer
              required:
              - podAffinityTerm
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                namespaces:
                  items:
                    type: string
                  type: array
                topologyKey:
                  type: string
              required:
              - topologyKey
              type: object
            type: array
        type: object
      podAntiAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                podAffinityTerm:
                  properties:
                    labelSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    namespaceSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    namespaces:
                      items:
                        type: string
                      type: array
                    topologyKey:
                      type: string
                  required:
                  - topologyKey
                  type: object
                weight:
                  format: int32
                  type: integer
              required:
              - podAffinityTerm
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                namespaces:
                  items:
                    type: string
                  type: array
                topologyKey:
                  type: string
              required:
              - topologyKey
              type: object
            type: array
        type: object
    type: object
  annotations:
    additionalProperties:
      type: string
    type: object
  apiserver:
    properties:
      groupPriorityMinimum:
        format: int32
        type: integer
      healthcheck:
        properties:
          enabled:
            type: boolean
        type: object
      servingCerts:
        properties:
          caCrt:
            type: string
          generate:
            type: boolean
          serverCrt:
            type: string
          serverKey:
            type: string
        required:
        - generate
        type: object
      useKubeapiserverFqdnForAks:
        type: boolean
      versionPriority:
        format: int32
        type: integer
    required:
    - groupPriorityMinimum
    - healthcheck
    - servingCerts
    - useKubeapiserverFqdnForAks
    - versionPriority
    type: object
  criticalAddon:
    type: boolean
  fullnameOverride:
    type: string
  image:
    properties:
      registry:
        type: string
      repository:
        type: string
      resources:
        properties:
          limits:
            additionalProperties:
              anyOf:
              - type: integer
              - type: string
              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
              x-kubernetes-int-or-string: true
            type: object
          requests:
            additionalProperties:
              anyOf:
              - type: integer
              - type: string
              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
              x-kubernetes-int-or-string: true
            type: object
        type: object
      securityContext:
        properties:
          allowPrivilegeEscalation:
            type: boolean
          capabilities:
            properties:
              add:
                items:
                  type: string
                type: array
              drop:
                items:
                  type: string
                type: array
            type: object
          privileged:
            type: boolean
          procMount:
            type: string
          readOnlyRootFilesystem:
            type: boolean
          runAsGroup:
            format: int64
            type: integer
          runAsNonRoot:
            type: boolean
          runAsUser:
            format: int64
            type: integer
          seLinuxOptions:
            properties:
              level:
                type: string
              role:
                type: string
              type:
                type: string
              user:
                type: string
            type: object
          seccompProfile:
            properties:
              localhostProfile:
                type: string
              type:
                type: string
            required:
            - type
            type: object
          windowsOptions:
            properties:
              gmsaCredentialSpec:
                type: string
              gmsaCredentialSpecName:
                type: string
              hostProcess:
                type: boolean
              runAsUserName:
                type: string
            type: object
        type: object
      tag:
        type: string
    required:
    - registry
    - repository
    - tag
    type: object
  imagePullPolicy:
    type: string
  imagePullSecrets:
    items:
      type: string
    type: array
  licenses:
    additionalProperties:
      type: string
    type: object
  logLevel:
    format: int32
    type: integer
  monitoring:
    properties:
      agent:
        enum:
        - prometheus.io
        - prometheus.io/operator
        - prometheus.io/builtin
        type: string
      serviceMonitor:
        properties:
          labels:
            additionalProperties:
              type: string
            type: object
        type: object
    required:
    - agent
    - serviceMonitor
    type: object
  nameOverride:
    type: string
  nodeSelector:
    additionalProperties:
      type: string
    type: object
  platform:
    properties:
      baseURL:
        type: string
      token:
        type: string
    required:
    - baseURL
    - token
    type: object
  podAnnotations:
    additionalProperties:
      type: string
    type: object
  podSecurityContext:
    properties:
      fsGroup:
        format: int64
        type: integer
      fsGroupChangePolicy:
        type: string
      runAsGroup:
        format: int64
        type: integer
      runAsNonRoot:
        type: boolean
      runAsUser:
        format: int64
        type: integer
      seLinuxOptions:
        properties:
          level:
            type: string
          role:
            type: string
          type:
            type: string
          user:
            type: string
        type: object
      seccompProfile:
        properties:
          localhostProfile:
            type: string
          type:
            type: string
        required:
        - type
        type: object
      supplementalGroups:
        items:
          format: int64
          type: integer
        type: array
      sysctls:
        items:
          properties:
            name:
              type: string
            value:
              type: string
          required:
          - name
          - value
          type: object
        type: array
      windowsOptions:
        properties:
          gmsaCredentialSpec:
            type: string
          gmsaCredentialSpecName:
            type: string
          hostProcess:
            type: boolean
          runAsUserName:
            type: string
        type: object
    type: object
  registryFQDN:
    type: string
  replicaCount:
    format: int32
    type: integer
  serviceAccount:
    properties:
      annotations:
        additionalProperties:
          type: string
        type: object
      create:
        type: boolean
      name:
        type: string
    required:
    - create
    type: object
  tolerations:
    items:
      properties:
        effect:
          type: string
        key:
          type: string
        operator:
          type: string
        tolerationSeconds:
          format: int64
          type: integer
        value:
          type: string
      type: object
    type: array
required:
- apiserver
- image
- imagePullPolicy
- monitoring
- platform
- registryFQDN
- replicaCount
- serviceAccount
type: object
