apiVersion: ui.k8s.appscode.com/v1alpha1
kind: FeatureSet
metadata:
  name: opscenter-datastore
spec:
  title: Databases
  description: |
    Manage production grade databases powered by KubeDB.
  icons:
  - src: https://cdn.appscode.com/k8s/icons/menu/cluster.svg
    type: image/svg+xml
  required: false
  requiredFeatures:
  - kubedb
  - kubedb-opscenter
  chart:
    name: uik8sappscodecom-featureset-opscenter-datastore-editor
    url: https://charts.appscode.com/stable/
    version: v2023.03.23
