apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: license-proxyserver
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    displayName: {{ .Chart.Name }}
    description: {{ .Chart.Description }}
  installStrategy:
    type: Placements
    placements:
      - name: {{ .Values.placement.name }}
        namespace: {{ .Release.Namespace }}
