project:
  name: Prometheus Proxy by AppsCode
  shortName: Prometheus Proxy
  url: https://github.com/bytebuilders
  description: ByteBuilders Prometheus Proxy
  app: a Prometheus Proxy
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: prom-proxy
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: prom-proxy
  namespace: ace-system
