apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-bind-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-bind-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-bind-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-bind-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "kube-bind-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.image.securityContext | nindent 12 }}
          image: {{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - server
            - --oidc-issuer-url={{ .Values.server.oidc.issuerURL }}
            - --oidc-callback-url={{ .Values.server.oidc.callbackURL }}
            - --pretty-name="{{ .Values.server.providerPrettyName }}
            - --namespace-prefix={{ .Values.server.namespacePrefix }}
            - --oidc-issuer-client-id={{ .Values.server.oidc.clientID }}
            - --oidc-issuer-client-secret={{ .Values.server.oidc.clientSecret }}
            - --cookie-signing-key={{ .Values.server.cookie.signingKey }}
            - --cookie-encryption-key={{ .Values.server.cookie.encryptionKey }}
            - --consumer-scope={{ .Values.server.consumerScope }}
            - --external-address={{ .Values.server.external.address }}
            - --external-server-name={{ .Values.server.external.serverName }}
            - --external-ca-file={{ .Values.server.external.CAFile }}
          env:
          - name: BIND_BACKEND_IMAGE
            value: { include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          ports:
          - containerPort: 3003
            name: http
            protocol: TCP
          resources:
            {{- toYaml .Values.image.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
