apiVersion: v2
name: capa-vpc-peering-operator
description: A Helm chart for CAPA VPC Peering Operator by AppsCode
type: application
version: v2023.03.23
appVersion: v0.0.1
home: https://github.com/bytebuilders/capa-vpc-peering-operator
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/bytebuilders/capa-vpc-peering-operator
maintainers:
- name: appscode
  email: support@appscode.com
