apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceOutlineFilter
metadata:
  name: kubedb.com-v1-mysqls-kubedb
spec:
  actions:
  - items:
      Configure Backup: true
      Instant Backup: true
      Restore: true
    name: Backups
    show: true
  - items:
      Reconfigure: true
      Restart: true
      Update Version: true
    name: Operations
    show: true
  - items:
      Scale Vertically: true
      Scale Storage: true
      Expand Volume: true
      Horizontal Scale: true
      Vertical Scale: true
    name: Scaling
    show: true
  - items:
      Compute: true
      Storage: true
    name: Autoscaling
    show: true
  - items:
      Monitoring: true
      TLS Configure: true
    name: Security & Monitoring
    show: true
  - items:
      Expose via Gateway: true
    name: Extras
    show: true
  header: true
  pages:
  - name: Overview
    sections:
    - blocks:
        Dashboards: true
        Nodes: true
      info:
        basic: true
        inCluster: true
        gateway: true
      insight: true
      show: true
    show: true
  - name: Insights
    sections:
    - blocks:
        Databases: true
        Grafana Dashboards: true
        Slow Queries: true
      info: {}
      insight: true
      show: true
    show: true
  - name: Users
    sections:
    - blocks:
        AppBindings: true
        MySQLRoles: true
        Root User: true
        SecretAccessRequests: true
        SecretEngines: true
        VaultServers: true
      info: {}
      insight: false
      show: true
    show: true
  - name: Operations
    sections:
    - blocks:
        Recent Operations: true
        Recommendations: true
      info: {}
      insight: false
      show: true
    show: true
  - name: Backup
    sections:
    - blocks:
        Backup Configuration: true
        CronJobs: true
        Recent Backups: true
        Recent Restores: true
        Repository: true
      info: {}
      insight: false
      show: true
    show: true
  - name: Backup (Legacy)
    sections:
    - blocks:
        Recent Backups: true
        Recent Restores: true
      info:
        basic: true
      insight: false
      show: true
    show: false
  - name: Security
    sections:
    - blocks:
        CVE Report: true
      info: {}
      insight: false
      name: CVE Report
      show: true
    - blocks:
        ClusterRoleBindings: true
        ClusterRoles: true
        RoleBindings: true
        Roles: true
        Service Account: true
      info: {}
      insight: false
      name: Access Control
      show: true
    - blocks:
        Certificates: true
        Cluster Issuer: true
        Issuer: true
        Secrets: true
      info: {}
      insight: false
      name: TLS
      show: true
    - blocks:
        Policy Report: true
      info: {}
      insight: false
      name: Policies
      show: true
    - blocks:
        Falco Events: true
      info: {}
      insight: false
      name: Runtime Security
      show: true
    show: false
  - name: Manifests
    sections:
    - info:
        basic: true
        manifests: true
      insight: false
      show: true
    show: false
  resource:
    group: kubedb.com
    kind: MySQL
    name: mysqls
    scope: Namespaced
    version: v1
  tabBar: true
