apiVersion: v2
name: catalog-manager
description: A Helm chart for Appcatalog Operator by AppsCode
type: application
version: v2024.2.11
appVersion: v0.0.1
home: https://github.com/bytebuilders/catalog-manager
icon: https://cdn.appscode.com/images/products/searchlight/icons/android-icon-192x192.png
sources:
- https://github.com/bytebuilders/catalog-manager
maintainers:
- name: appscode
  email: support@appscode.com
