project:
  name: Appcatalog by AppsCode
  shortName: Appcatalog
  url: https://github.com/bytebuilders/catalog-manager
  description: Appcatalog for Kubernetes
  app: an Appcatalog
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: catalog-manager
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: catalog-manager
  namespace: ace
