apiVersion: apps/v1
kind: {{ .Values.controller.kind }}
metadata:
  name: {{ include "smtprelay.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smtprelay.labels" . | nindent 4 }}
spec:
  {{- if and (eq .Values.controller.kind "Deployment") (not .Values.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "smtprelay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smtprelay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "appscode.serviceAccountName" . }}
      {{- if eq "true" ( include "distro.openshift" . ) }}
      securityContext:
        {{- toYaml (omit .Values.podSecurityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 8 }}
      {{- else }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if eq "true" ( include "distro.openshift" . ) }}
          securityContext:
            {{- toYaml (omit .Values.image.securityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 12 }}
          {{- else }}
          securityContext:
            {{- if .Values.smtp.tls.enable }}
              {{- $_ := set .Values.securityContext "runAsUser" 0 }}
              {{- $_ := set .Values.securityContext "runAsGroup" 0 }}
            {{- end }}
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ include "image.registry" . }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - -config
          - /etc/smtprelay/smtprelay.ini
          ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
            {{- if .Values.hostPort.enabled }}
            hostPort: {{ .Values.service.port }}
            {{- end }}
          - name: metrics
            containerPort: 8080
            protocol: TCP
         {{- if .Values.smtp.tls.enable }}
          - name: tls
            containerPort: 465
            protocol: TCP
            {{- if .Values.hostPort.enabled }}
            hostPort: 465
            {{- end }}
          - name: starttls
            containerPort: 587
            protocol: TCP
            {{- if .Values.hostPort.enabled }}
            hostPort: 587
            {{- end }}
         {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/smtprelay
            readOnly: true
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: {{ include "smtprelay.fullname" . }}-config
          {{- if .Values.smtp.tls.enable }}
          - secret:
              name: {{ default (printf "%s-cert" (include "smtprelay.fullname" .)) .Values.smtp.tls.secret.name }}
              items:
              - key: tls.crt
                path: pki/tls.crt
              - key: tls.key
                path: pki/tls.key
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
