apiVersion: v2
name: cert-manager-webhook-ace
description: A webhook to use AppsCode DNS Proxy for Cloudfare as a DNS issuer for
  cert-manager
home: https://github.com/appscode-cloud/cert-manager-webhook-ace
type: application
version: v2026.1.15
appVersion: v0.0.2
keywords:
- cert-manager
- letsencrypt
- tls
sources:
- https://github.com/appscode-cloud/cert-manager-webhook-ace
maintainers:
- name: appscode
  email: support@appscode.com
