apiVersion: v1
description: AppsCode SaaS Provider
name: service-provider
version: v2026.2.16
appVersion: v0.0.2
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/stash/service-provider-icon.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
