annotations:
  charts.openshift.io/name: ace-installer-certified-crds
apiVersion: v2
appVersion: v2026.1.15
description: Chart containing only CRDs from ace-installer chart
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
kubeVersion: '>=1.28.0'
maintainers:
- email: support@appscode.com
  name: appscode
name: ace-installer-certified-crds
sources:
- https://github.com/appscode-cloud/installer
version: 2026.1.15
