{{ if (index .Values "httpRoute" "enabled") }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "ace.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.httpRoute.gatewayClassName }}
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: {{ include "ace.fullname" . }}-cert
        namespace: {{ .Release.Namespace }}
    allowedRoutes:
      namespaces:
        from: Same
  - allowedRoutes:
      namespaces:
        from: Same
      kinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
    name: nats-tcp
    port: 4222
    protocol: TCP
  - allowedRoutes:
      namespaces:
        from: Same
      kinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
    name: s3proxy-tcp
    port: 4224
    protocol: TCP
{{- end }}
