apiVersion: v2
name: acerproxy
description: A Helm chart for Rancher aware proxy of ACE api
type: application
version: v2026.2.16
appVersion: v0.2.0
home: https://github.com/kubedb/acerproxy
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
sources:
- https://github.com/kubedb/acerproxy
maintainers:
- name: appscode
  email: support@appscode.com
