{{- with (index .Values "helm" "releases" "panopticon") }}
{{- if .enabled }}

{{ $defaults := dict "registryFQDN" (include "registry.ghcr" $) }}

{{ $platformCA := dig "releases" "ace" "values" "global" "infra" "tls" "ca" "cert" "" $.Values.helm }}
{{ if $platformCA }}
{{ $defaults = mergeOverwrite $defaults (dict "platform" (dict "caBundle" $platformCA)) }}
{{ end }}

{{ $vals := dig "values" dict . }}
{{ $vals = mergeOverwrite $defaults $vals }}

{{- if eq (include "distro.openshift" $) "true" }}
{{ $vals = mergeOverwrite $vals (dict "distro" .Values.options.distro) }}
{{- end }}

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: panopticon
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/component: panopticon
    app.kubernetes.io/part-of: opscenter-observability
spec:
  interval: 5m
  timeout: 30m
  releaseName: panopticon
  targetNamespace: monitoring
  storageNamespace: monitoring
  install:
    createNamespace: {{ $.Values.helm.createNamespace }}
    # crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  dependsOn:
  - name: opscenter-features
    namespace: {{ $.Release.Namespace }}
  - name: license-proxyserver
    namespace: {{ $.Release.Namespace }}
  chart:
    spec:
      chart: panopticon
      version: {{ .version | quote }}
      sourceRef:
        kind: HelmRepository
        name: appscode-charts-oci
        namespace: {{ $.Release.Namespace }}
{{- with $vals }}
  {{- dict "values" . | toYaml | nindent 2 }}
{{- end }}

{{- end }}
{{- end }}
