kind: Deployment
apiVersion: apps/v1
metadata:
  name: license-proxyserver-addon-manager
  namespace: license-proxyserver-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-proxyserver-addon-manager
  template:
    metadata:
      labels:
        app: license-proxyserver-addon-manager
    spec:
      serviceAccountName: license-proxyserver-addon-manager
      containers:
        - name: license-proxyserver-addon-manager
          image: ghcr.io/appscode/license-proxyserver-addon:v0.0.1
          imagePullPolicy: IfNotPresent
