apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "platform-api.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
spec:
  # for headless service
  clusterIP: None
  # port needed to create SRV records, SRV records have pod DNS name
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
    {{- end }}
  # selector needed to create pods dns name
  selector:
    {{- include "platform-api.selectorLabels" . | nindent 4 }}
