apiVersion: v2
appVersion: v2025.12.15
description: ACE Installer
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
maintainers:
- email: support@appscode.com
  name: appscode
name: ace-installer-certified
sources:
- https://github.com/appscode-cloud/installer
type: application
version: v2025.12.15
