annotations:
  charts.openshift.io/name: ace-installer-certified
apiVersion: v2
appVersion: v2026.1.15
description: ACE Installer
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
kubeVersion: '>=1.28.0-0'
maintainers:
- email: support@appscode.com
  name: appscode
name: ace-installer-certified
sources:
- https://github.com/appscode-cloud/installer
type: application
version: 2026.1.15
