{{- if (index .Values "gateway" "enabled") }}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "offline-license-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "offline-license-server.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ace
    namespace: ace
    sectionName: https

  hostnames:
  {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
  {{- end }}

  rules:
  {{- range .Values.gateway.hosts }}
    {{- range .paths }}
  - matches:
    - path:
        type: PathPrefix
        value: {{ .path }}
    backendRefs:
    - group: ""
      kind: Service
      name: {{ include "offline-license-server.fullname" $ }}
      namespace: {{ $.Release.Namespace }}
      port: {{ $.Values.service.port }}
      weight: 1
    {{- end }}
  {{- end }}

{{- end }}
