apiVersion: v2
name: opscenter-features
description: ByteBuilders Opscenter Configuration
type: application
version: v2022.06.14
appVersion: v2022.06.14
home: https://github.com/bytebuilders
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
sources:
- https://github.com/bytebuilders/installer
maintainers:
- name: appscode
  email: support@appscode.com
