apiVersion: v2
name: opscenter-features
description: ACE Opscenter Configuration
type: application
version: v2025.12.15
appVersion: v0.28.0
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud/installer
maintainers:
- name: appscode
  email: support@appscode.com
