# Default values for monitoring-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: opscenter

global:
  # License for the product.
  # Get a license by following the steps from [here](https://kubedb.com/docs/latest/setup/install/enterprise#get-a-trial-license).
  # Example:
  # helm install appscode/kubedb \
  #   --set-file global.license=/path/to/license/file
  # or
  # helm install appscode/kubedb \
  #   --set global.license=<license file content>
  license: ""

  # Docker registry used to pull KubeDB related images
  registry: ""

  # Docker registry fqdn used to pull KubeDB related images.
  # Set this to use docker registry hosted at ${registryFQDN}/${registry}/${image}
  registryFQDN: ""

  # Specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  #
  # Example:
  # helm template charts/kubedb \
  #   --set global.imagePullSecrets[0].name=sec0 \
  #   --set global.imagePullSecrets[1].name=sec1
  imagePullSecrets: []

  monitoring:
    # Name of monitoring agent (one of "prometheus.io", "prometheus.io/operator", "prometheus.io/builtin")
    agent: ""
    serviceMonitor:
      # Specify the labels for ServiceMonitor.
      # Prometheus crd will select ServiceMonitor using these labels.
      # Only usable when monitoring agent is `prometheus.io/operator`.
      labels: {}
    alert:
      ## Labels for default rules
      labels: {}

panopticon:
  enabled: true

ui-presets:
  enabled: true

grafana:
  default: false
  url: ""
  service:
    scheme: ""
    name: ""
    namespace: ""
    port: ""
    path: ""
    query: ""
  # The HTTP basic authentication username for the Prometheus server.
  basicAuth:
    # The HTTP basic authentication username for the Prometheus server.
    username: ""
    # The HTTP basic authentication password for the Prometheus server.
    password: ""
  # The bearer token for the Prometheus server.
  bearerToken: ""
  tls:
    # The CA cert to use for the Prometheus server.
    ca: ""
    # The client cert to use for communicating with the Prometheus server.
    cert: ""
    # The client key to use for communicating with the Prometheus server.
    key: ""
    # The server name which will be used to verify the Prometheus server address.
    serverName: ""
    # To skip tls verification when communicating with the Prometheus server.
    insecureSkipTLSVerify: false
  dashboard:
    datasource: ""
    folderID: 0
prometheus:
  default: false
  url: ""
  service:
    scheme: ""
    name: ""
    namespace: ""
    port: ""
    path: ""
    query: ""
  # The HTTP basic authentication username for the Prometheus server.
  basicAuth:
    # The HTTP basic authentication username for the Prometheus server.
    username: ""
    # The HTTP basic authentication password for the Prometheus server.
    password: ""
  # The bearer token for the Prometheus server.
  bearerToken: ""
  tls:
    # The CA cert to use for the Prometheus server.
    ca: ""
    # The client cert to use for communicating with the Prometheus server.
    cert: ""
    # The client key to use for communicating with the Prometheus server.
    key: ""
    # The server name which will be used to verify the Prometheus server address.
    serverName: ""
    # To skip tls verification when communicating with the Prometheus server.
    insecureSkipTLSVerify: false
