{{- if not .Values.kubeconfigSecretName }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: license-proxyserver-addon-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: license-proxyserver-addon-manager
subjects:
  - kind: ServiceAccount
    name: license-proxyserver-addon-manager
    namespace: license-proxyserver-addon

{{- end }}
