apiVersion: v2
name: platform-ui
description: A Helm chart for Kubernetes
type: application
version: v2025.12.15
appVersion: 1.9.0
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
