project:
  name: Platform UI by AppsCode
  shortName: Platform UI
  url: https://github.com/bytebuilders
  description: ByteBuilders Platform UI
  app: a Platform UI
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: platform-ui
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: platform-ui
  namespace: kubeops
