properties:
  affinity:
    properties:
      nodeAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                preference:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchFields:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                  type: object
                  x-kubernetes-map-type: atomic
                weight:
                  format: int32
                  type: integer
              required:
              - preference
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            properties:
              nodeSelectorTerms:
                items:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchFields:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                  type: object
                  x-kubernetes-map-type: atomic
                type: array
            required:
            - nodeSelectorTerms
            type: object
            x-kubernetes-map-type: atomic
        type: object
      podAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                podAffinityTerm:
                  properties:
                    labelSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    namespaceSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    namespaces:
                      items:
                        type: string
                      type: array
                    topologyKey:
                      type: string
                  required:
                  - topologyKey
                  type: object
                weight:
                  format: int32
                  type: integer
              required:
              - podAffinityTerm
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                  x-kubernetes-map-type: atomic
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                  x-kubernetes-map-type: atomic
                namespaces:
                  items:
                    type: string
                  type: array
                topologyKey:
                  type: string
              required:
              - topologyKey
              type: object
            type: array
        type: object
      podAntiAffinity:
        properties:
          preferredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                podAffinityTerm:
                  properties:
                    labelSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    namespaceSelector:
                      properties:
                        matchExpressions:
                          items:
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                        matchLabels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    namespaces:
                      items:
                        type: string
                      type: array
                    topologyKey:
                      type: string
                  required:
                  - topologyKey
                  type: object
                weight:
                  format: int32
                  type: integer
              required:
              - podAffinityTerm
              - weight
              type: object
            type: array
          requiredDuringSchedulingIgnoredDuringExecution:
            items:
              properties:
                labelSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                  x-kubernetes-map-type: atomic
                namespaceSelector:
                  properties:
                    matchExpressions:
                      items:
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  type: object
                  x-kubernetes-map-type: atomic
                namespaces:
                  items:
                    type: string
                  type: array
                topologyKey:
                  type: string
              required:
              - topologyKey
              type: object
            type: array
        type: object
    type: object
  autoscaling:
    properties:
      enabled:
        type: boolean
      maxReplicas:
        type: integer
      minReplicas:
        type: integer
      targetCPUUtilizationPercentage:
        type: integer
      targetMemoryUtilizationPercentage:
        type: integer
    required:
    - enabled
    - maxReplicas
    - minReplicas
    type: object
  fullnameOverride:
    type: string
  image:
    properties:
      pullPolicy:
        type: string
      registry:
        type: string
      repository:
        type: string
      tag:
        type: string
    required:
    - pullPolicy
    - registry
    - repository
    - tag
    type: object
  imagePullSecrets:
    items:
      type: string
    type: array
  nameOverride:
    type: string
  nodeSelector:
    additionalProperties:
      type: string
    type: object
  platform:
    properties:
      deploymentContext:
        properties:
          hostedDomain:
            type: string
          proxyServiceDomain:
            type: string
          requesterEmail:
            type: string
          requesterName:
            type: string
          token:
            type: string
        required:
        - hostedDomain
        - proxyServiceDomain
        - requesterEmail
        - requesterName
        - token
        type: object
      deploymentType:
        enum:
        - Hosted
        - SelfHostedProduction
        - SelfHostedDemo
        type: string
      domain:
        type: string
    required:
    - deploymentType
    - domain
    type: object
  podAnnotations:
    additionalProperties:
      type: string
    type: object
  podSecurityContext:
    properties:
      fsGroup:
        format: int64
        type: integer
      fsGroupChangePolicy:
        type: string
      runAsGroup:
        format: int64
        type: integer
      runAsNonRoot:
        type: boolean
      runAsUser:
        format: int64
        type: integer
      seLinuxOptions:
        properties:
          level:
            type: string
          role:
            type: string
          type:
            type: string
          user:
            type: string
        type: object
      seccompProfile:
        properties:
          localhostProfile:
            type: string
          type:
            type: string
        required:
        - type
        type: object
      supplementalGroups:
        items:
          format: int64
          type: integer
        type: array
      sysctls:
        items:
          properties:
            name:
              type: string
            value:
              type: string
          required:
          - name
          - value
          type: object
        type: array
      windowsOptions:
        properties:
          gmsaCredentialSpec:
            type: string
          gmsaCredentialSpecName:
            type: string
          hostProcess:
            type: boolean
          runAsUserName:
            type: string
        type: object
    type: object
  registryFQDN:
    type: string
  replicaCount:
    type: integer
  resources:
    properties:
      limits:
        additionalProperties:
          anyOf:
          - type: integer
          - type: string
          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
          x-kubernetes-int-or-string: true
        type: object
      requests:
        additionalProperties:
          anyOf:
          - type: integer
          - type: string
          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
          x-kubernetes-int-or-string: true
        type: object
    type: object
  securityContext:
    properties:
      allowPrivilegeEscalation:
        type: boolean
      capabilities:
        properties:
          add:
            items:
              type: string
            type: array
          drop:
            items:
              type: string
            type: array
        type: object
      privileged:
        type: boolean
      procMount:
        type: string
      readOnlyRootFilesystem:
        type: boolean
      runAsGroup:
        format: int64
        type: integer
      runAsNonRoot:
        type: boolean
      runAsUser:
        format: int64
        type: integer
      seLinuxOptions:
        properties:
          level:
            type: string
          role:
            type: string
          type:
            type: string
          user:
            type: string
        type: object
      seccompProfile:
        properties:
          localhostProfile:
            type: string
          type:
            type: string
        required:
        - type
        type: object
      windowsOptions:
        properties:
          gmsaCredentialSpec:
            type: string
          gmsaCredentialSpecName:
            type: string
          hostProcess:
            type: boolean
          runAsUserName:
            type: string
        type: object
    type: object
  service:
    properties:
      port:
        type: integer
      type:
        type: string
    required:
    - port
    - type
    type: object
  serviceAccount:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  settings:
    properties:
      caProviderClass:
        type: string
      secretName:
        properties:
          grafanaConfig:
            type: string
          nats:
            type: string
          objstore:
            type: string
          platformConfig:
            type: string
        required:
        - grafanaConfig
        - nats
        - objstore
        - platformConfig
        type: object
    required:
    - caProviderClass
    - secretName
    type: object
  tolerations:
    items:
      properties:
        effect:
          type: string
        key:
          type: string
        operator:
          type: string
        tolerationSeconds:
          format: int64
          type: integer
        value:
          type: string
      type: object
    type: array
required:
- autoscaling
- image
- platform
- replicaCount
- service
- serviceAccount
- settings
type: object
