apiVersion: v2
name: accounts-ui
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "v2022.05.27.4"
home: https://github.com/bytebuilders
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/bytebuilders
maintainers:
- name: appscode
  email: support@appscode.com
