project:
  name: Accounts UI by AppsCode
  shortName: Accounts UI
  url: https://github.com/bytebuilders
  description: Accounts UI
  app: a Accounts UI
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: accounts-ui
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: accounts-ui
  namespace: ace-system
