apiVersion: v2
name: ace-installer
description: ACE Installer
type: application
version: v2026.2.16
appVersion: v2026.2.16
kubeVersion: '>=1.28.0-0'
annotations:
  charts.openshift.io/name: ace-installer
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud/installer
maintainers:
- name: appscode
  email: support@appscode.com
