apiVersion: v2
name: ace-installer
description: ACE Installer
type: application
version: v2025.12.15
appVersion: v2025.12.15
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud/installer
maintainers:
- name: appscode
  email: support@appscode.com
